### ISSUE TITLE
Error: 'Device' object has no attribute '_device'

### ISSUE THREAD

**Issue by reza3320** [EstebanMagallonPerez/touchPad#3]
I faced[ this error](https://github.com/EstebanMagallonPerez/touchPad/issues/2) then I removed the print part so I can see the result of the code but it is not still working and give me another error.

```py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstr$
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "touchpadnewcommit.py", line 163, in doEverything
    dev._device.detach_kernel_driver(interface)
AttributeError: 'Device' object has no attribute '_device'
```

**EDIT**:
I had a problem with `windll` before and after research I found out that I shoud use `linux.so` instead, but It wasn't work again so I changed this:
```py
from ctypes import windll, Structure, c_long, byref
```
**to this:** 
```py
from ctypes import *
```

**Comment by EstebanMagallonPerez** [comment]
I never tested this on linux, so if you are able to get this to work let me know and I will update the page to mention compatibility

**Comment by reza3320** [comment]
> I never tested this on linux, so if you are able to get this to work let me know and I will update the page to mention compatibility
It didn't even work in windows for me :(
but I'm trying, I will notify you.
